In [241]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 100

In [242]:
df = pd.read_csv('C:/Users/tyler.wong/Desktop/happy_teacher/pilot_datatsets/dailyActivity_merged.csv')

In [243]:
df2 = pd.read_excel('C:/Users/tyler.wong/Desktop/happy_teacher/Copy of Fitabase and Consent Dates File 2.1.23.xlsx')

In [244]:
df

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Floors,CaloriesBMR,MarginalCalories,RestingHeartRate
0,10101,10/5/2022,4606,3.02,3.02,0.0,0.57,0.51,1.94,0.0,10,11,102,1317,1916,4,1504,273,78.0
1,10101,10/6/2022,2690,1.75,1.75,0.0,0.00,0.00,1.75,0.0,0,0,117,526,1880,4,1504,242,75.0
2,10101,10/7/2022,4143,2.72,2.72,0.0,0.00,0.00,2.71,0.0,0,0,260,1180,2286,2,1504,479,76.0
3,10101,10/8/2022,703,0.46,0.46,0.0,0.00,0.00,0.46,0.0,0,0,34,1406,1608,2,1504,71,NaN
4,10101,10/9/2022,0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0,0,1,1439,1509,0,1504,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3356,10804,12/8/2022,6727,4.47,4.47,0.0,0.00,0.00,4.46,0.0,0,0,335,671,1970,1,1283,390,54.0
3357,10804,12/9/2022,8083,5.39,5.39,0.0,0.50,0.39,4.48,0.0,10,13,326,613,2106,4,1283,507,53.0
3358,10804,12/10/2022,6294,4.26,4.26,0.0,0.00,0.00,4.25,0.0,0,0,367,662,2120,10,1283,497,55.0
3359,10804,12/11/2022,3686,2.47,2.47,0.0,0.53,0.23,1.71,0.0,27,21,174,555,1933,4,1283,434,55.0
3360,10804,12/12/2022,4645,3.17,3.17,0.0,0.00,0.00,3.16,0.0,0,0,243,271,1335,4,870,275,57.0

In [245]:
df2

,ID,Consent,Consent Date,Fitabase,Fitabase Date,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,10101,True,2022-09-26,True,2022-10-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10102,True,2022-09-30,True,2022-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10103,True,2022-09-30,True,2022-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10104,True,2022-09-30,True,2022-10-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10106,True,2022-09-30,True,2022-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,10107,True,2022-09-30,True,2022-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,10108,True,2022-09-30,True,2022-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10109,True,2022-09-30,True,2022-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10204,True,2022-10-03,True,2022-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10205,True,2022-10-03,True,2022-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10301,True,2022-10-04,True,2022-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,10302,True,2022-10-04,True,2022-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,10303,True,2022-10-04,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,10304,True,2022-10-04,True,2022-10-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,10305,True,2022-10-04,True,2022-10-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,10306,True,2022-10-04,True,2022-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,10307,True,2022-10-04,True,2022-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,10401,True,2022-10-11,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,10402,True,2022-10-11,True,2022-10-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,10403,True,2022-10-11,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,10404,True,2022-10-11,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,10405,True,2022-10-11,True,2022-10-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,10406,True,2022-10-11,True,2022-10-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,10407,True,2022-10-11,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,10408,True,2022-10-11,True,2022-10-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,10409,True,2022-10-11,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,10410,True,2022-10-11,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,10412,True,2022-10-11,True,2022-10-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,10413,True,2022-10-11,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,10415,True,2022-10-26,True,2022-10-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,10501,True,2022-10-13,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,10502,True,2022-10-13,True,2022-10-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,10503,True,2022-10-13,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,10504,True,2022-10-13,True,2022-10-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,10505,True,2022-10-13,True,2022-10-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,10601,True,2022-10-14,True,2022-10-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,10602,True,2022-10-14,True,2022-10-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,10603,True,2022-10-14,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,10604,True,2022-10-14,True,2022-10-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,10605,True,2022-10-14,True,2022-10-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,10606,True,2022-10-14,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,10607,True,2022-10-14,True,2022-10-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,10608,True,2022-10-14,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,10609,True,2022-10-14,True,2022-10-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,10610,True,2022-10-14,True,2022-10-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,10611,True,2022-10-14,True,2022-10-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,10612,True,2022-10-14,True,2022-10-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,10613,True,2022-10-14,True,2022-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,10614,True,2022-10-14,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,10615,True,2022-10-19,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,10616,True,2022-10-19,True,2022-10-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,10701,True,2022-10-19,True,2022-10-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,10702,True,2022-10-19,True,2022-10-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,10703,True,2022-10-19,True,2022-10-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,10704,True,2022-10-19,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,10801,True,2022-10-19,True,2022-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,10802,True,2022-10-19,True,2022-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,10803,True,2022-10-19,True,2022-10-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,10804,True,2022-10-19,True,2022-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [246]:
df2_sorted = df2.sort_values('ID')

In [261]:
unique_ids = df['Id'].unique()
dfs = {}
dfs_consent = {}
for id in unique_ids:
    curr_df = df.query("Id == @id")[["ActivityDate","TotalSteps"]]
    curr_df['ActivityDate'] = pd.to_datetime(curr_df['ActivityDate'])
    consent_df = df2_sorted.query("ID == @id")[["Consent Date"]]
    consent_df['Consent Date'] = pd.to_datetime(consent_df['Consent Date'])
    dfs[id] = curr_df
    dfs[id].reset_index(drop=True, inplace=True)
    dfs_consent[id] = consent_df
#unique_ids

In [262]:
#dfs[10103]
#dfs_consent[10103]["Consent Date"]
#dfs[10102]["ActivityDate"]
#dfs_consent[10101]["Consent Date"]
#dfs[10102]["ActivityDate"][0] = dfs[10102]["ActivityDate"].iloc[0] - dfs_consent[10102]["Consent Date"].iloc[0]

In [263]:
for id in unique_ids:
    consent_date = dfs_consent[id]["Consent Date"].iloc[0]
    for  i in range(dfs[id]["ActivityDate"].size):
        activity_date = dfs[id]["ActivityDate"].iloc[i]
        dfs[id]["ActivityDate"].iloc[i] = activity_date - consent_date
        days_int = int(dfs[id]["ActivityDate"][i].days)
        dfs[id]["ActivityDate"].iloc[i] = days_int

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [264]:
for id in unique_ids:
    empty_rows = pd.DataFrame(index=range(100 - dfs[id].shape[0]))
    dfs[id] = pd.concat([dfs[id], empty_rows], ignore_index=True)
    dfs[id] = dfs[id].shift(dfs[id]["ActivityDate"][0])

dfs[10101]

   ActivityDate  TotalSteps
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
5           NaN         NaN
6           NaN         NaN
7           NaN         NaN
8           NaN         NaN
9             9      4606.0
10           10      2690.0
11           11      4143.0
12           12       703.0
13           13         0.0
14           14      5998.0
15           15      5479.0
16           16      6264.0
17           17      4931.0
18           18      5730.0
19           19         0.0
20           20         0.0
21           21         0.0
22           22         0.0
23           23      4416.0
24           24      3166.0
25           25      5739.0
26           26         0.0
27           27         0.0
28           28         0.0
29           29         0.0
30           30         0.0
31           31      1949.0
32          NaN         NaN
33          NaN         NaN
34          NaN         NaN
35          NaN         NaN
36          NaN         NaN
37          NaN         NaN
38          NaN         NaN
39          NaN         NaN
40          NaN         NaN
41          NaN         NaN
42          NaN         NaN
43          NaN         NaN
44          NaN         NaN
45          NaN         NaN
46          NaN         NaN
47          NaN         NaN
48          NaN         NaN
49          NaN         NaN
50          NaN         NaN
51          NaN         NaN
52          NaN         NaN
53          NaN         NaN
54          NaN         NaN
55          NaN         NaN
56          NaN         NaN
57          NaN         NaN
58          NaN         NaN
59          NaN         NaN
60          NaN         NaN
61          NaN         NaN
62          NaN         NaN
63          NaN         NaN
64          NaN         NaN
65          NaN         NaN
66          NaN         NaN
67          NaN         NaN
68          NaN         NaN
69          NaN         NaN
70          NaN         NaN
71          NaN         NaN
72          NaN         NaN
73          NaN         NaN
74          NaN         NaN
75          NaN         NaN
76          NaN         NaN
77          NaN         NaN
78          NaN         NaN
79          NaN         NaN
80          NaN         NaN
81          NaN         NaN
82          NaN         NaN
83          NaN         NaN
84          NaN         NaN
85          NaN         NaN
86          NaN         NaN
87          NaN         NaN
88          NaN         NaN
89          NaN         NaN
90          NaN         NaN
91          NaN         NaN
92          NaN         NaN
93          NaN         NaN
94          NaN         NaN
95          NaN         NaN
96          NaN         NaN
97          NaN         NaN
98          NaN         NaN
99          NaN         NaN

In [234]:
dfs[10804].shape[0]

42

In [236]:
dfs[10804]

   ActivityDate  TotalSteps
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
5           NaN         NaN
6           NaN         NaN
7           NaN         NaN
8           NaN         NaN
9           NaN         NaN
10          NaN         NaN
11          NaN         NaN
12          NaN         NaN
13           13      7900.0
14           14      6918.0
15           15      5870.0
16           16      2750.0
17           17     11142.0
18           18      4987.0
19           19      6749.0
20           20      6252.0
21           21      7396.0
22           22      7149.0
23           23     16283.0
24           24      5697.0
25           25      3316.0
26           26      7613.0
27           27      5930.0
28           28      6289.0
29           29     12107.0
30           30      5661.0
31           31      4745.0
32           32     14361.0
33           33      6593.0
34           34      6057.0
35           35      3175.0
36           36      2268.0
37           37     13935.0
38           38      4020.0
39           39     11920.0
40           40      7012.0
41           41      8728.0
42           42      6090.0
43           43     14195.0
44           44     17300.0
45           45      1512.0
46           46     12229.0
47           47      7257.0
48           48      6851.0
49           49      7755.0
50           50      6727.0
51           51      8083.0
52           52      6294.0
53           53      3686.0
54           54      4645.0
55          NaN         NaN
56          NaN         NaN
57          NaN         NaN
58          NaN         NaN
59          NaN         NaN
60          NaN         NaN
61          NaN         NaN
62          NaN         NaN
63          NaN         NaN
64          NaN         NaN
65          NaN         NaN
66          NaN         NaN
67          NaN         NaN
68          NaN         NaN
69          NaN         NaN
70          NaN         NaN
71          NaN         NaN
72          NaN         NaN
73          NaN         NaN
74          NaN         NaN
75          NaN         NaN
76          NaN         NaN
77          NaN         NaN
78          NaN         NaN
79          NaN         NaN
80          NaN         NaN
81          NaN         NaN
82          NaN         NaN
83          NaN         NaN
84          NaN         NaN
85          NaN         NaN
86          NaN         NaN
87          NaN         NaN
88          NaN         NaN
89          NaN         NaN
90          NaN         NaN
91          NaN         NaN
92          NaN         NaN
93          NaN         NaN
94          NaN         NaN
95          NaN         NaN
96          NaN         NaN
97          NaN         NaN
98          NaN         NaN
99          NaN         NaN